name: OBAmazeingTimer
version: 1.0
description: Timer for solving A-Maze-Ing maze on the build server and recording attempt times on signs
author: F451
api-version: "1.21"
website: https://ob-mc.net
main: net.obmc.OBAmazeingTimer.OBAmazeingTimer
depend: []
commands:
